## Préambule
site_name: My web site
site_description: a site about stg.
site_author: Raj

theme:
  name: readthedocs # mkdocs


## Architecture
nav:
  - Home: index.md
  - Cheat-Sheet: cheat_sheet.md


## Extensions